title      = "Blues Improvisation Complete (Eb)"
composer   = "Jeff Harrington"
subtitle   = "A Blues Scale Exercises"
paperSize = "letter"

#-------------------------------------------------------------------------------
[exercise_1]
staffRelative = "a'"
tabRelative = "a"
tabMinimumFret = "#3"
music = '''{
    a8   c(    d)    ees(  e)   g(    a)   c(   |
    d)   ees(  d)    c(    a)   g(    e)   ees( |
    d)   c(    a)    g(    e)   ees(  d)   c(   |
    d)   ees(  e)    g(    a2)                  |
}'''

#-------------------------------------------------------------------------------
[exercise_2]
staffRelative = "a'"
tabRelative = "a"
tabMinimumFret = "#3"
music = '''{ 
    \tuplet 3/2 { a8(   c)   d }
    \tuplet 3/2 { ees(  e)   g }
    \tuplet 3/2 { a(    c)   d } 
    \tuplet 3/2 { ees(  d)   c } |
    \tuplet 3/2 { a(    g)   e }
    \tuplet 3/2 { ees(  d)   c }
    \tuplet 3/2 { a(    g)   e }
    \tuplet 3/2 { ees(  d)   c } |
    \tuplet 3/2 { d(    ees) e }
    \tuplet 3/2 { g(    a)   c }
    a2 |
}'''

#-------------------------------------------------------------------------------
[exercise_3]
staffRelative = "a'"
tabRelative = "a"
tabMinimumFret = "#5"
music = '''{ 
    \tuplet 3/2 { a8 g a }
    \tuplet 3/2 { c a c }
    \tuplet 3/2 { d c d } 
    \tuplet 3/2 { ees d ees } |
    \tuplet 3/2 { e ees e }
    \tuplet 3/2 { g e g }
    \tuplet 3/2 { a g a }
    \tuplet 3/2 { c a c } |
    \tuplet 3/2 { d c d }
    ees2. |
}'''

#-------------------------------------------------------------------------------
[exercise_4]
staffRelative = "a''"
tabRelative = "a'"
tabMinimumFret = "#3"
music = '''{ 
    \tuplet 3/2 { c8 d c }
    \tuplet 3/2 { a c a }
    \tuplet 3/2 { g a g } 
    \tuplet 3/2 { e g e } |
    \tuplet 3/2 { ees e ees }
    \tuplet 3/2 { d e d }
    \tuplet 3/2 { c d c } 
    \tuplet 3/2 { a c a } | \break
    \tuplet 3/2 { g a g }
    \tuplet 3/2 { e g e }
    \tuplet 3/2 { ees e ees } 
    \tuplet 3/2 { d e d } |
    \tuplet 3/2 { ees e g }
    a2. |
}'''
pageBreak = true

#-------------------------------------------------------------------------------
[exercise_5]
staffRelative = "a"
tabRelative = "a"
tabMinimumFret = "#3"
music = '''{ 
    a8   c(    d)    ees(  e)   ees(    d)   c(   |
    d)   ees(  e)    g(    a)   g(      e)   ees( |
    e)   g(    a)    c(    d)   c(      a)   a(   |
    a2)  r2 |
}'''


#-------------------------------------------------------------------------------
[exercise_6]
staffRelative = "d'''"
tabRelative = "d''"
tabMinimumFret = "#3"
music = '''{ 
    d8   c(    a)    g(    e)   g(      a)   c(   |
    a)   g(    e)    ees(  d)   e(      ees) g(   |
    e)   ees(  d)    c(    a)   c(      d)   ees( |  \break
    d)   c(    a)    g(    e)   g(      a)   c(   |
    a)   g(    e)    ees(  d)   ees(    e)   d(   |
    e)   ees(  d)    c(    d)   ees(    e)   g(   |
    a2)  r2 |
}'''
